# Setup
title:            Rock Night
tagline:          'Tudo da night Rock n Roll'
description:      'Blog sobre a Night Rock'
url:              http://rocknight.github.io
author:           'Marquinhus Gonçalves'
email:            eu@marquinhusgoncalves.com

# google_analytics:
account:          UA-103801239-1

# Build settings
markdown:       kramdown
highlighter:    rouge
permalink:      /:title

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
